image: ghcr.io/diamondlightsource/python-copier-template-example:0.5.4

hostNetwork: false

# 37889 is p49-detector
# securityContext:
#   runAsUser: 37889
#   runAsGroup: 37889
securityContext:
  runAsUser: 0
  runAsGroup: 0

resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: beamline
              operator: In
              values:
                - bl49p

tolerations:
  - key: beamline
    operator: Equal
    value: bl49p
    effect: NoSchedule
  - key: location
    operator: Equal
    value: bl49p
    effect: NoSchedule
  - key: nodetype
    operator: Equal
    value: training-rig
    effect: NoSchedule
