# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.9
_src_path: gh:epics-containers/services-template-helm
cluster_name: pollux
cluster_namespace: p49-beamline
cluster_type: dls_cluster
description: p49 IOC Instances and Services
git_platform: github.com
github_org: epics-containers
ioc_group: p49
location: bl49p
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
repo_uri: https://github.com/epics-containers/p49-services
