apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: p49-beamline
spec:
  encryptedData:
    POSTGRES_DB: 
    USERDB_USER: 
    
    USER_PASS: 
    ADMIN_PASS: 
