apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tiled-secret
  namespace: p49-beamline
spec:
  encryptedData:
    TILED_SINGLE_USER_API_KEY: AgB1re6FL+yXwAPAkpdm0nPNFag+6dfCeubb8KH2bDktDtn9NE9r0bH2cI5R+oQWEWqOn7zSlHggJX1ivLmFpaspMn4aSMk7II4oEA+QUnFbmIxFokxpwqMZW+A7Hp9cT+wD8THO8ZEhg/2rFvQBa2ZuVmEbj9NjevFPuUzTHlAT7Zh6+J3vtiwy9XWFeyVNYv+jdXBfqSrFeI0B/TGHFBBRAQa0EbSyerJgkH2XCHTyugl5UbAPmlYXd9fmPKF63ID+LvAtAey5A69t0qVtbBLNwhaXdbAkUAJzmZdv8OcHpGy3OJuPTyooEoITLw2F16W+jRgs+gKRCwOeFrg7adAYLdfsIOnpJQ6g16YQDCYZKd78qKzIFZjcOpsFc31BEtrERzyFlBqJD8xQS3pUouPoPj5RiQrxx6gmS5yZ0jcntFC2v0zQx578ym7fDRrbOtkmPy+r97SHiXv63VfaJD0x0or/TfxLOCPTLiKu5ftufp6rEGqxcrx3zi97pZQ35XaP1am7PhKQMx5gDuhAchaIh0+q3BJ3CT1wqEDpT1JTkw629MJlzG999H1oEaKb393jGImsLJVgrkqDx5ZoF5V8+7uZgi6ytvl1qmoBNByY6ytbhHxSQrkhHNpwMtBHv/KGQyV6sxb2P2zyhjMemn7WpYTiEMR6xoPdSEI5s5Wd7inmUm4mi6xbiNXWinxSplZy4YIEi9smhYkCULXnZtS1jCr/a6Jf6tNiBq+wGnzIiag2uHZrmnGvwxetn9UKjQa/lIjUGIEaLf1TwATzUwqB
