# A Helm Chart for an IOC instance
apiVersion: v2
name: ec-service
version: 1.0.0
type: application
dependencies:
  - name: odin-eiger
    version: 0.4.0-beta7
    repository: "oci://ghcr.io/diamondlightsource"
