apiVersion: v2
name: p49-blueapi
description: blueapi deployed for p49 with authentication and tracing

version: 0.8.0
# When we deploy with the edge-containers-cli we override this on the command line.
# Direct deployment with Helm will use the default beta value.
appVersion: 0.0.1b1

type: application

dependencies:
  - name: blueapi
    version: "0.20.0"
    repository: "oci://ghcr.io/diamondlightsource/charts"
