apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blueapi-secret
  namespace: p49-beamline
spec:
  encryptedData:
    client-secret: 
    cookie-secret: AgBNDIzXzYMPyLG7TPmCc81o/cXbPbH43jHnkttUPvP23Z1YilbPjPhzhHXFTpxAZoGZtVWOE9llih4cj7QQrT592FDpNNfahyDfJoFnGQ40ZDltLF3nL/xnGpLcoVohp449/HGkgf/utyBfd5IdZbE31QDzLsuwcrnV5xWOIE8n1EofLgIhmlRr31Ul5fX9/VzEC5i4ZVnwcebHACRb47WZLDRpEf/ENPacq6qwsviX/9H9rI44qGos96Ye3TmDKs0PITqSxkR9fuCnHH9RWrI7Ew6CZhM6YWo/ZBNb0d14OGOjMolUyC4dV8pq/KawbP0ir7R70knhvseVqG/i6p8BQOFBGGCdRwkjUsNI1RosOVV2HVbg1enmFj7FMk3Vn08UPf0JwOYBNorRnFfBU6stxZi5AQlzUk2l5XctHJUjmzkdbvtkY87ZDr3yewnFoi93Viv/WwydZ4Z1VTqDqcdWhebJ38qwVUy6Gkqe6sutyf2vNfsPGDoKSroVGd9qKb8nsGjFBRkjAyp+6K0ehNN5FJ/CPglJu9yR2kZzEZzDvuckx13NpbdrbeTfnhv2oNbmxWkcl9yY2Oc/SGMr+vdAUUWYUf9G7lHBlZVhThwnRmSfB4Z8QT7RVgatW8q+3bYjxDNIZ/yYVzi8T1duFiP67FjX9uhOQjw20e64Vd+TY9w9pu0DX681FZXBXag8G6kzyX9pHxmNNbQCOWGUXTtSwOoEof/bGkXvPzP6Fc3ADGB7Mbuh03KRxqqUvA==
    tiled-writer-secret: 