apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p48-blueapi-my-volume
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
