apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
    enabled: 'true'
    ioc_group: p49
    is_ioc: 'true'
    location: bl49p
  name: {{ .Release.Name }}
  namespace: p49-beamline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
        ioc_group: p49
        is_ioc: 'true'
        location: bl49p
        rollme: goWO0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beamline
                    operator: In
                    values:
                      - bl49p
      containers:
        - command:
           - bash
          args:
           - "-c"
           - "/epics/gateway -sport 9064 -cip 172.23.255.255 -pvlist /config/pvlist -access /config/access -log /dev/stdout -debug 1"
          env:
            - name: IOC_NAME
              value: {{ .Release.Name }}
            - name: IOC_LOCATION
              value: bl49p
            - name: IOC_GROUP
              value: p49
          image: {{ .Values.image }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /config
              name: config-volume
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 3
      tolerations:
        - effect: NoSchedule
          key: beamline
          operator: Equal
          value: bl49p
        - effect: NoSchedule
          key: location
          operator: Equal
          value: bl49p
        - effect: NoSchedule
          key: nodetype
          operator: Equal
          value: training-rig
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-config
          name: config-volume